package com.drWhoAPI.drWhoAPI.models.enums;

import com.fasterxml.jackson.annotation.JsonValue;

public enum Series {
    SEASON1("Season 1"),
    SEASON2("Season 2"),
    SEASON3("Season 3"),
    SEASON4("Season 4"),
    SEASON5("Season 5"),
    SEASON6("Season 6"),
    SEASON7("Season 7"),
    SEASON8("Season 8"),
    SEASON9("Season 9"),
    SEASON10("Season 10"),
    SEASON11("Season 11"),
    SEASON12("Season 12"),
    SEASON13("Season 13"),
    SEASON14("Season 14"),
    SEASON15("Season 15"),
    SEASON16("Season 16"),
    SEASON17("Season 17"),
    SEASON18("Season 18"),
    SEASON19("Season 19"),
    SEASON20("Season 20"),
    SEASON21("Season 21"),
    SEASON22("Season 22"),
    SEASON23("Season 23"),
    SEASON24("Season 24"),
    SEASON25("Season 25"),
    SEASON26("Season 26"),
    TVM("The TV Movie"),
    SERIES1("Series 1"),
    SERIES2("Series 2"),
    SERIES3("Series 3"),
    SERIES4("Series 4"),
    TENNANTSPECIALS("2008 - 2010 Specials"),
    SERIES5("Series 5"),
    SERIES6A("Series 6A"),
    SERIES6B("Series 6B"),
    SERIES7A("Series 7A"),
    SERIES7B("Series 7B"),
    FIFTYSPECIALS("Fiftieth Anniversary Specials"),
    SERIES8("Series 8"),
    SERIES9("Series 9"),
    SERIES10("Series 10"),
    SERIES11("Series 11"),
    SERIES12("Series 12"),
    SERIES13("Flux/Series 13"),
    WHITTAKERSPECIALS("2022 Specials"),
    SIXTYSPECIALS("Sixtieth Anniversary Specials"),
    SEASON12024("Series 1 (2024)"),
    SEASON22025("Series 2 (2025)"),
    BBCRADIO("BBC Radio"),
    TARGET("Target Books"),
    NEWADVENTURES("The New Adventures"),
    MISSINGADVENTURES("The Missing Adventures"),
    EDA("Eighth Doctor Adventures"),
    PDA("Past Doctor Adventures"),
    NSA("New Series Adventures"),
    STANDALONE_BBC_BOOK("Standalone BBC Novel"),
    TELOS("Telos Novella"),
    BBV("BBV Productions"),
    IDW("IDW Comics"),
    TITAN("Titan Comics"),
    DWM("Doctor Who Magazine Comics"),
    BBCCOMIC("BBC Comic Book"),
    BIGFINISH("Big Finish"),
    BF_FIRST("The First Doctor Adventures (Big Finish)"),
    BF_SECOND("The Second Doctor Adventures (Big Finish)"),
    BF_THIRD("The Third Doctor Adventures (Big Finish)"),
    BF_FOURTH("The Fourth Doctor Adventures (Big Finish)"),
    BF_FIFTH("The Fifth Doctor Adventures (Big Finish)"),
    BF_SIXTH("The Sixth Doctor Adventures (Big Finish)"),
    BF_SEVENTH("The Seventh Doctor Adventures (Big Finish)"),
    BF_EIGHTH("The Eighth Doctor Adventures (Big Finish)"),
    BF_NINTH("The Ninth Doctor Adventures (Big Finish)"),
    BF_TENTH("The Tenth Doctor Adventures (Big Finish)"),
    BF_WAR("The War Doctor (Big Finish)"),
    BF_DR_CHRONICLES("The Doctor Chronicles (Big Finish)"),
    BF_AUDIO_NOVELS("Audio Novels"),
    BF_MONTHLY("The Monthly Adventures (Big Finish)"),
    BF_EARLY("The Early Adventures (Big Finish)"),
    BF_LOST("Lost Stories (Big Finish)"),
    BF_COMPANION_CHRONICLES("Companion Chronicles (Big Finish)"),
    BF_NOVEL_ADAPTATIONS("Novel Adaptations (Big Finish)"),
    BF_HINCHCLIFFE("Philip Hinchcliffe Presents (Big Finish)"),
    BF_SHORT_TRIPS("Short Trips"),
    BF_UNBOUND("Unbound (Big Finish)"),
    BF_ONCE_FUTURE("Once and Future (Big Finish)"),
    TIME_LORD_VICTORIOUS("Time Lord Victorious"),
    DESTINY_DOCTORS("Destiny of the Doctor"),
    OTHER("Other");


    private final String value;

    Series(String value) {
        this.value = value;
    }

    @JsonValue
    String getValue() {
        return this.value;
    }
}
